version: '3'

tasks:
  build:
    cmds:
      - go build -o app cmd/server/main.go

  test:
    cmds:
      - go test -v ./...

  test:commodity:get:
    cmds:
      - curl -X GET http://localhost:8080/api/v1/commodities

  test:commodity:post:
    cmds:
    - |
      curl -X POST http://localhost:8080/api/v1/commodities -H "Content-Type: application/json" -d '{"name": "test", "value": 100}'

  lint:
    cmds:
      - golangci-lint run

  run:
    cmds:
      - docker-compose up --build

  clear:
    cmds:
      - docker-compose down -v