version: '3'

tasks:
  build:
    desc: "Build the application"
    watch: true
    sources:
      - '**/*.go'
    cmds:
      - go build -o app cmd/server/main.go

  test:
    desc: Run the tests
    cmds:
      - go test -v ./...

  test:commodity:all:
    desc: GET All Commodities, {page} {per_page} {order_by} {direction}
    cmds:
    - |
      set -- {{.CLI_ARGS}}
      curl -i -X GET "http://localhost:8080/api/v1/commodities?page=${1}&per_page=${2}&order_by=${3},${4}"

  test:commodity:get:
    desc: GET Commodity, {id}
    cmds:
    - |
      set -- {{.CLI_ARGS}}
      curl -i -X GET http://localhost:8080/api/v1/commodities/${1}
 
  test:commodity:post:
    desc: POST a test Commodity, {name} {unitmass} {unitvolume}
    cmds:
    - |
      set -- {{.CLI_ARGS}}
      curl -i -X POST http://localhost:8080/api/v1/commodities -H "Content-Type: application/json" -d "{\"name\": \"${1}\", \"unitmass\": ${2}, \"unitvolume\": ${3}}"

  test:commodity:delete:
    desc: DELETE Commodity, {id}
    cmds:
    - |
      set -- {{.CLI_ARGS}}
      curl -i -X DELETE http://localhost:8080/api/v1/commodities/${1}

  test:solarSystem:all:
    desc: GET All Solar Systems, {page} {per_page} {order_by} {direction}
    cmds:
    - |
      set -- {{.CLI_ARGS}}
      curl -i -X GET "http://localhost:8080/api/v1/solarSystems?page=${1}&per_page=${2}&order_by=${3},${4}"

  test:solarSystem:get:
    desc: GET Solar System, {id}
    cmds:
    - |
      set -- {{.CLI_ARGS}}
      curl -i -X GET http://localhost:8080/api/v1/solarSystems/${1} 

  test:solarSystem:post:
    desc: POST a test Solar System, {name}
    cmds:
    - |
      set -- {{.CLI_ARGS}}
      curl -i -X POST http://localhost:8080/api/v1/solarSystems -H "Content-Type: application/json" -d "{\"name\": \"${1}\"}"

  test:solarSystem:delete:
    desc: DELETE Solar System, {id}
    cmds:
    - |
      set -- {{.CLI_ARGS}}
      curl -i -X DELETE http://localhost:8080/api/v1/solarSystems/${1}

  lint:
    desc: Run the linter
    cmds:
      - golangci-lint run

  run:
    desc: Build and run the application
    cmds:
      - docker-compose up --build

  clear:
    desc: Clear the database, delete all containers and volumes
    cmds:
      - docker-compose down -v

  database:migration:create:
    desc: Create a new migration, {numerical identifier} {name}
    cmds:
    - |
      set -- {{.CLI_ARGS}}
      touch migrations/${1}_${2}.up.sql
      touch migrations/${1}_${2}.down.sql
