CREATE TABLE IF NOT EXISTS commodities (
    ID uuid,
    Name VARCHAR(255),
    Unit_Mass DOUBLE PRECISION,
    Unit_Volume DOUBLE PRECISION,
    Created_At TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);
