CREATE TABLE IF NOT EXISTS commodities (
    ID uuid,
    Name VARCHAR(255),
    UnitMass DOUBLE PRECISION,
    UnitVolume DOUBLE PRECISION,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);
