CREATE TABLE IF NOT EXISTS solar_systems (
    ID uuid,
    Name VARCHAR(255),
    Created_At TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);
